loglevel: info # increase to trace for more verbose output
write-directory: evaluation_results
write: true # Change to false if you don't want to write the results to disk
output: yaml # Change to json if you want CLI and written output in json format
services:
  # if there are multiple entries here, multiple services can be run via Privateer
  # while running via debug, only one service can be run at a time using --service=<service_name>
  
  <service_name>: # unique name/id for the evaluation
    
    plugin: github-repo # required while running via Privateer
    
    # The policy section may be set at the top level if assessing multiple services via privateer
    policy:
      catalogs:
        - OSPS_B # currently this is the only available catalog to assess against
      applicability:
        - maturity-1
        # - maturity-2
        # - maturity-3
    
    # All variables are required to run the evaluation
    vars:
      owner: <github org or user name>
      repo: <github repo name>
      token: <classic token with permissions repo + admin:org>

