issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:privateerproj/privateer:pull_request
claim_pattern:
  job_workflow_ref: privateerproj/privateer/.github/workflows/ci.yml@.*

permissions:
  contents: read
