## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
jobs:
  lint_pr_title:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: github/ospo-reusable-workflows/.github/workflows/pr-title.yaml@6f158f242fe68adb5a2698ef47e06dac07ac7e71
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
